### ISSUE TITLE
Z output not uniform

### ISSUE THREAD

**Issue by RCLaurence** [majroy/d3dslic3r#3]
The out line z values exported and the in fill z values exported can be different even within the same slice.

![image](https://github.com/user-attachments/assets/3b6f89a9-c70b-4e70-b462-94a1ff0fe18d)

Also the infill currently has 100% overlap with the out line. The infill lines need to be truncated at each end.

**Comment by majroy** [comment]
Item 1) Re. incorrect z values, fixed - error found in `d3dslic3r_common.get_intersections()`, z value was being double padded.
Item 2) Error in using midline instead of inner periphery of projected bead now implemented:
![Screenshot 2024-07-31 16 38 44](https://github.com/user-attachments/assets/305075dd-1435-4285-a205-fa7e73d5659a)

**Comment by majroy** [comment]
Fixed with v.0.3post1
