### ISSUE TITLE
Infill paths not correctly re-orienting with rotational offset on some outlines

### ISSUE THREAD

**Issue by majroy** [majroy/d3dslic3r#5]
See issue here:
![image](https://github.com/user-attachments/assets/542d234f-d9eb-4afa-a9e6-a57cf85717f4)
Confirmed that still occurs with 'Path outline' enabled, and on outlines that have been processed by an alpha shape, see settings above to replicate.

**Comment by leoxiaoyuan** [comment]
Tried to reproduce the issue while keeping generated paths not transformed back, found there were no intersections on the bottom contour.

<img width="981" alt="Screenshot 2024-08-04 at 18 31 58" src="https://github.com/user-attachments/assets/7ca94a6c-c653-4c11-a680-bcffbb48a423">

Tried to give yrange a larger range. (change yrange = [limits[2]*1.2,limits[3]*1.2] to yrange = [limits[2]*1.2-100,limits[3]*1.2+100]) Problem solved.

<img width="950" alt="Screenshot 2024-08-04 at 18 37 25" src="https://github.com/user-attachments/assets/742dcff3-bfc7-477d-9acb-182c121d6f11">

Any reason why to choose this range? Is that OK to just give it a very big range?

**Comment by majroy** [comment]
Main issue attributed to simultaneous move to centroid and rotation for path calculation. A two-stage move, first to the centroid and then rotated by the target theta value seems to fix the main issue noted for most values of theta Leaving open as there is still a problem:
![image](https://github.com/user-attachments/assets/96da63bb-6e61-4b82-8b47-d1da56a15f60)

**Comment by leoxiaoyuan** [comment]
<img width="1083" alt="Screenshot 2024-08-05 at 09 32 48" src="https://github.com/user-attachments/assets/dbe15e15-7748-4829-9940-9d3bb5ea2c41">

Problem location: As shown in the figure, the intersection points of that line are marked with "o", the starting points of that contour is marked with 🌟. Because the starting point f the contour is in the middle, which would cause problem of the intersection points order. Therefore, if the **'pack up/pair intersections for line paths'** is used, it will cause this problem.

Solution: reorder the contour to make sure the starting point always has the largest y value:
    X = do_transform(outline,trans)
    # Find the index of the point with the maximum y value
    max_y_index = np.argmax(X[:, 1])
    # Reorder the contour points to start from the point with the maximum y value
    reordered_contour = np.concatenate((X[max_y_index:-1], X[:max_y_index]), axis=0)
    # Add the starting point to the end to close the contour
    X = np.vstack([reordered_contour, reordered_contour[0]])
    
<img width="976" alt="Screenshot 2024-08-05 at 10 15 13" src="https://github.com/user-attachments/assets/8c7f68cc-1912-431b-a37a-c7cc2158ff36">

**Comment by leoxiaoyuan** [comment]
Previous method did not solve the problem indeed, it will cause:
![image](https://github.com/user-attachments/assets/f459eed8-114a-4560-ba7a-93459650231d)

So, instead, reorder the intersection points directly with: 
intersections = intersections[np.lexsort((intersections[:, 1], intersections[:, 0]))]

![image](https://github.com/user-attachments/assets/c61772af-086c-4e96-85c6-b98290189a84)
![image](https://github.com/user-attachments/assets/e2565ef6-7c5c-4f5f-b93d-ed2dc6433034)

Seems working for both cases.
